env_files = [".env"]

[env]
VERSION = "${CARGO_MAKE_CRATE_VERSION}"
IMAGE = "${DOCKER_IMAGE_PATH}:${VERSION}"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build-wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.optimize-wasm]
command = "wasm-opt"
args = [
    "-Os",
    "target/wasm32-unknown-unknown/release/openapi_path_filter.wasm",
    "-o",
    "target/wasm32-unknown-unknown/release/openapi_path_filter.optimized.wasm",
]

[tasks.build-docker]
command = "docker"
args = ["build", "-t", "${IMAGE}", "."]

[tasks.push-docker]
command = "docker"
args = ["push", "${IMAGE}"]

[tasks.all]
dependencies = [
    "test",
    "build-wasm",
    "optimize-wasm",
    "build-docker",
    "push-docker",
]

[tasks.clean-all]
dependencies = ["clean", "all"]

[tasks.show-env]
description = "환경 변수 출력하기"
script = '''
#!/usr/bin/env bash
echo "CARGO_MAKE_WORKING_DIRECTORY: ${CARGO_MAKE_WORKING_DIRECTORY}"
echo "CARGO_MAKE_LOAD_ENV_FILES: ${CARGO_MAKE_LOAD_ENV_FILES}"
echo "DOCKER_IMAGE_PATH: ${DOCKER_IMAGE_PATH}"
'''
