env_files = [".env"]

[env]
VERSION = "${CARGO_MAKE_CRATE_VERSION}"
IMAGE = "${DOCKER_IMAGE_PATH}:${VERSION}"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build-wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.optimize-wasm]
command = "wasm-opt"
args = [
    "-Os",
    "target/wasm32-unknown-unknown/release/openapi_endpoint_filter.wasm",
    "-o",
    "target/wasm32-unknown-unknown/release/openapi_endpoint_filter.optimized.wasm",
]

[tasks.build-docker]
command = "docker"
args = ["build", "-t", "${IMAGE}", "."]

[tasks.push-docker]
command = "docker"
args = ["push", "${IMAGE}"]

[tasks.deploy]
dependencies = [
    "clean",
    "test",
    "build-wasm",
    "optimize-wasm",
    "build-docker",
    "push-docker",
]

[tasks.deploy-skip-test]
dependencies = ["build-wasm", "optimize-wasm", "build-docker", "push-docker"]

[tasks.deploy-clean]
dependencies = ["clean", "deploy"]

[tasks.show-env]
description = "환경 변수 출력하기"
script = '''
#!/usr/bin/env bash
echo "DOCKER_IMAGE_PATH: ${DOCKER_IMAGE_PATH}"
'''
