apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: gateway
  url: anyflow/openapi-endpoint-filter:0.2.5
  imagePullPolicy: Always
  phase: STATS # (Recommended) Apply before the istio.stats filter
  failStrategy: FAIL_OPEN # (Recommended) Bypass the filter on fatal errors
  match:
    - mode: CLIENT_AND_SERVER # WasmPlugin default mode is CLIENT_AND_SERVER
  # priority: 10
  pluginConfig:
    cacheSize: 5 # (Optional) LRU cache size for path matching results. Default is 1024. Set 0 to disable cache.
    services: # (Required) Register OpenAPI path templates for multiple services
      - name: dockebi # (Required) Service name, added as x-service-name header
        paths: # (Required) List OpenAPI path templates as-is
          /dockebi/v1/stuff: {}
          /dockebi/v1/stuff/{id_}: {}
          /dockebi/v1/stuff/{id_}/child/{child_id}/hello: {}
      - name: userservice
        paths:
          /users: {}
          /users/{id}: {}
          /users/{id}/profile: {}
      - name: productservice
        paths:
          /products: {}
          /products/{product_id}: {}
          /categories/{category_id}/products: {}
