apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-endpoint-filter # (Optional) Change if you want a custom name
  namespace: cluster # (Optional) Set if you want a specific namespace (defaults to current)
spec:
  selector:
    matchLabels:
      app: gateway # (Required) Update to match your proxy/workload labels
  url: anyflow/openapi-endpoint-filter:0.4.0 # (Required) Update to the image tag you want to use
  imagePullPolicy: Always
  phase: STATS # (Recommended) Apply before the istio.stats filter
  failStrategy: FAIL_OPEN # (Recommended) Bypass the filter on fatal errors
  match:
    - mode: CLIENT_AND_SERVER # WasmPlugin default mode is CLIENT_AND_SERVER
  # priority: 10
  pluginConfig:
    preserveExistingHeaders: true # (Optional) Preserve existing headers. Default is true.
    useHostInMatch: true # (Optional) Match request host against servers.url host. Default is true.
    services: # (Required) Update with your OpenAPI paths/servers
      - name: dockebi # (Required) Service name, added as x-service-name header
        servers: # (Optional, OpenAPI 3.0+) Server URLs for host/basePath matching
          - url: https://{env}.example.com/v1
            variables:
              env:
                default: api
                enum: [api, staging]
        paths: # (Required) List OpenAPI path templates as-is
          /dockebi/v1/stuff:
            get: {}
            post: {}
          /dockebi/v1/stuff/{id_}:
            get: {}
          /dockebi/v1/stuff/{id_}/child/{child_id}/hello: {}
      - name: userservice
        paths:
          /users: {}
          /users/{id}: {}
          /users/{id}/profile: {}
      - name: productservice
        paths:
          /products: {}
          /products/{product_id}: {}
          /categories/{category_id}/products: {}
