apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openapi-path-filter
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: gateway
  url: anyflow/openapi-path-filter:0.1.9
  imagePullPolicy: Always
  phase: AUTHN # 실행 단계 설정 - Istio 트레이싱 필터보다 앞서 실행되도록
  priority: 10 # 같은 phase 내에서의 우선순위 (높을수록 먼저 실행)
  pluginConfig:
    cache_size: 5
    services:
      - name: dockebi
        paths:
          /dockebi/v1/stuff: {}
          /dockebi/v1/stuff/{id_}: {}
          /dockebi/v1/stuff/{id_}/child/{child_id}/hello: {}
